services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        NGINX_PORT: ${NGINX_PORT}
    container_name: nginx
    image: nginx:42
    restart: always
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file: .env

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        PHP_FPM_PORT: ${PHP_FPM_PORT}
    container_name: wordpress
    image: wordpress:42
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file: .env
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_name
      - db_user
      - db_password
      - db_root_password

  redis:
    depends_on:
      - wordpress
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    image: redis:42
    restart: always
    networks:
      - inception

  adminer:
    depends_on:
      - mariadb
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer:42
    restart: always
    networks:
      - inception

  # website:
  #   depends_on:
  #     - nginx
  #   build:
  #     context: ./requirements/bonus/website
  #   container_name: website
  #   image: website:42
  #   restart: always
  #   networks:
  #     - inception
  #   env_file: .env

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jqueijo-/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jqueijo-/data/mariadb

secrets:
  db_name:
    file: ../secrets/dbName.txt
  db_user:
    file: ../secrets/dbUser.txt
  db_password:
    file: ../secrets/dbPassword.txt
  db_root_password:
    file: ../secrets/dbRootPassword.txt
  wp_admin_user:
    file: ../secrets/wpAdminUser.txt
  wp_admin_password:
    file: ../secrets/wpAdminPassword.txt
  wp_admin_email:
    file: ../secrets/wpAdminEmail.txt
  wp_user:
    file: ../secrets/wpUser.txt
  wp_user_password:
    file: ../secrets/wpUserPassword.txt
