services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/nginx.conf
    networks:
      - inception

networks:
  inception:
    driver: bridge
    name: inception
